"""Added updated_at field to the Todo model

Revision ID: 32d4d8361b21
Revises: 9cd731aabcdc
Create Date: 2023-07-04 07:59:36.752003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d4d8361b21'
down_revision = '9cd731aabcdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), server_default='2023-07-04 07:59:36.639176', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    # ### end Alembic commands ###
