"""Add sub property to the user model

Revision ID: 3989dd3c4f5a
Revises: 541f9ed7326d
Create Date: 2023-06-29 08:43:53.694724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3989dd3c4f5a'
down_revision = '541f9ed7326d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###
