"""Updated category_name field in the Category model

Revision ID: a7fa5729262f
Revises: 4ebad6c310ee
Create Date: 2023-07-04 14:08:47.612707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fa5729262f'
down_revision = '4ebad6c310ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.drop_column('categories', 'categoryName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('categoryName', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'category_name')
    # ### end Alembic commands ###
