"""Removed Todo relation from the User model

Revision ID: c6ef387ce7c3
Revises: a7fa5729262f
Create Date: 2023-07-04 22:05:46.132091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ef387ce7c3'
down_revision = 'a7fa5729262f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
