"""Added filename property to the Image model

Revision ID: cdcc43111898
Revises: f2c13850a0b6
Create Date: 2023-07-05 10:05:29.363435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcc43111898'
down_revision = 'f2c13850a0b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
