name: Coverage Report

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: cimg/python:3.11
    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: optipy_db_test
          POSTGRES_USER: optipy_db_test_user
          POSTGRES_PASSWORD: optipy_db_test_123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      # - name: Set up Python environment
      #   run: |
      #     source ./env/bin/activate
        
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env.test file
        run: |
          echo 'DB_USER="optipy_db_test_user"' >> .env.test
          echo 'DB_PASS="optipy_db_test_123"' >> .env.test
          echo 'DB_NAME="optipy_db_test"' >> .env.test
          echo 'DB_HOST="localhost"' >> .env.test
          echo 'DB_PORT=5432' >> .env.test
          echo '' >> .env.test
          echo 'AUTH0_DOMAIN="test.eu.auth0.com"' >> .env.test
          echo 'AUTH0_API_AUDIENCE="https://auth0.optipy.app"' >> .env.test
          echo 'AUTH0_ALGORITHMS="RS256"' >> .env.test
          echo 'AUTH0_ISSUER="https://test.eu.auth0.com/"' >> .env.test
          echo '' >> .env.test
          echo 'AWS_URL="http://localhost:4566"' >> .env.test
          echo 'AWS_ACCESS_KEY_ID="local-aws-key"' >> .env.test
          echo 'AWS_SECRET_ACCESS_KEY="local-secret-key"' >> .env.test
          echo 'AWS_REGION_NAME="eu-north-1"' >> .env.test

      - name: Install and run AWS LocalStack
        run: |
          pip install localstack
          docker pull localstack/localstack
          localstack start -d

          echo "Waiting for LocalStack to startup..."
          localstack wait -t 30
          echo "LocalStack startup complete"
          
      - name: Run tests with pytest
        run: |
          pytest